trigger:
  branches:
    include:
      - main
      - release/*

pool:
  vmImage: ubuntu-latest

stages:
# -------- BUILD --------
- stage: Build
  displayName: Build azuredevopstest
  jobs:
    - job: Build
      steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '18.x'

        - script: |
            npm install
            npm run build
          displayName: Install & Build React App

        - task: PublishBuildArtifacts@1
          inputs:
            pathToPublish: build
            artifactName: drop

# -------- DEV DEPLOY --------
- stage: Deploy_Dev
  displayName: Deploy to Dev
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
  variables:
    - group: dev-vars
  jobs:
    - deployment: DevDeploy
      environment: dev
      strategy:
        runOnce:
          deploy:
            steps:
              - download: current
                artifact: drop

              - task: AzureWebApp@1
                inputs:
                  azureSubscription: $(azureSubscription)
                  appName: $(webAppName)
                  package: $(Pipeline.Workspace)/drop

# -------- QA DEPLOY --------
- stage: Deploy_QA
  displayName: Deploy to QA
  condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')
  variables:
    - group: qa-vars
  jobs:
    - deployment: QADeploy
      environment: qa
      strategy:
        runOnce:
          deploy:
            steps:
              - download: current
                artifact: drop

              - task: AzureWebApp@1
                inputs:
                  azureSubscription: $(azureSubscription)
                  appName: $(webAppName)
                  package: $(Pipeline.Workspace)/drop
